// flow-typed signature: 29b29e87a011c8e826888a210790de4d
// flow-typed version: <<STUB>>/gulp-concat_v2.6.1/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-concat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-concat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-concat/index' {
  declare module.exports: $Exports<'gulp-concat'>;
}
declare module 'gulp-concat/index.js' {
  declare module.exports: $Exports<'gulp-concat'>;
}
