// flow-typed signature: 706d218527d45062d5f1b6d5d9bf0a66
// flow-typed version: <<STUB>>/simplemde-lite_v1.0.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simplemde-lite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simplemde-lite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'simplemde-lite/dist/simplemde.min' {
  declare module.exports: any;
}

declare module 'simplemde-lite/gulpfile' {
  declare module.exports: any;
}

declare module 'simplemde-lite/src/js/codemirror/tablist' {
  declare module.exports: any;
}

declare module 'simplemde-lite/src/js/simplemde' {
  declare module.exports: any;
}

// Filename aliases
declare module 'simplemde-lite/dist/simplemde.min.js' {
  declare module.exports: $Exports<'simplemde-lite/dist/simplemde.min'>;
}
declare module 'simplemde-lite/gulpfile.js' {
  declare module.exports: $Exports<'simplemde-lite/gulpfile'>;
}
declare module 'simplemde-lite/src/js/codemirror/tablist.js' {
  declare module.exports: $Exports<'simplemde-lite/src/js/codemirror/tablist'>;
}
declare module 'simplemde-lite/src/js/simplemde.js' {
  declare module.exports: $Exports<'simplemde-lite/src/js/simplemde'>;
}
